- README.md
> Add `osantana/prettyconf`

- README.md
> Added rocketchat, tsuru, django-react-boilerplate

- README.md
> Rename section flutter to dart

- README.md
> Adding Glorious Demo developed by Rafael Camargo

- README.md
> Added splinter, HTTPretty and lettuce

- README.md
**Obs:**
* Projects that have grown a lot in the Delphi community, and presented at major events such as Embarcadero Conference, CodeRage, ACBr Day.
* The RESTRequest4Delphi Project, although it does not have 100 stars, but it is very good, very simple to implement, and it has grown a lot too.
* Sorry I didn't do a PR for each item. I saw this contribution guide only at the end.
> Added Delphi session

- README.md
> Added browser gem

- README.md
> Added clappr

- README.md
> Added ffmpeg-libav

- README.md
> Added django-tenant-schemas

- README.md
> Added vscode-project-manager

- README.md
> Added vagrant-lxc

- README.md
> Added bullet-train.zsh

- .github/pull_request_template.md
- README.md
Just resolve conflicts and sync for #44
> feat: change list format

- README.md
> Add Node Cron by Lucas Merencia

- .github/pull_request_template.md
- README.md
Hi! Great stuff over here. I'm just sending some grammar adjustments in the main documentation. Cheers :tada:
-> `As a measurement`, `measurement` is an adjective. So either we define a noun, like `as a measurement system` or we use it as a verb, as my suggestion.
-> We must add an article to this;
-> as `personal` is a consonant sounded word, we must use `a` instead of `an`;
-> Here is just a minor typo fixing.
-> this is not entirely wrong but in this form sounds more natural to what you meant.
-> As we are making reference to git conflicts and not a specific conflict it would be more appropriate to use it in the plural form.
-> It's also not wrong but usually you use the `do` for something in the same phrase and close to relating. As you are referring to the list it's a bit better to …
> English grammar adjustments

- README.md
> Add DevHub

- README.md
> adding sharer.js

- README.md
> adding magictools list

- README.md
> add(feat): jsdocs

- README.md
> Added 33-js-concepts and fast-memoize.js

- README.md
Also, React95 won as ["Fun side project of the year"](https://twitter.com/ReactSummit/status/1116707269956251648), at React Summit in Amsterdam 👏  🍾
> Add React95

- README.md
Adding first Java project! 🤓 
Done!
> adding web-budget

- README.md
> Added fklearn by Nubank

- README.md
> Add clojure section with Nubank projects

- README.md
> Add modelo-de-contrato by apsantos-dev

- README.md
GitHub page: https://github.com/balde/balde
Docs: https://balde.rgm.io/
> Adds Balde

- README.md
> Added creditcard.js by ContaAzul

- README.md
> Dracula Theme

- README.md
- [x ] The project was created by the developers born in Brazil
- [x ] The project can't be just a personal, experimental or sample project
- [ x] The project has more than **100 stars** on Github
- [ x] Place them in alphabetical order
- [ x] One repository per PR/contribution - _avoid conflicts and simplify review_
- [ x] Check if your suggestion follows our pattern (title, description, badge), you need to add double blank space after ending line of each line
If they meet the …
> Added NLua link

- README.md
https://github.com/boppreh/keyboard
https://github.com/boppreh
> Added "keyboard", by BoppreH

- README.md
~~- [ ] The project was created by the developers born in Brazil
~~- [ ] The project can't be just a personal, experimental or sample project
~~- [ ] The project has more than **100 stars** on Github
~~- [ ] Place them in alphabetical order
~~- [ ] One repository per PR/contribution - _avoid conflicts and simplify review_
> Fix/move stars of Balde in a new line

- README.md
> Add PHP debugger in terminal

- README.md
> Alphabetical sections order

- README.md
> Add node4noobs

- README.md
> Added python rows

- README.md
> Added teresa by LuizaLabs

- README.md
> docs: fix svelte-loadable description

- README.md
> Add 'learn Go with tests' project

- README.md
> Add python-decouple

- README.md
> Added SpeakerFight

- README.md
> Add gabrielfalcao/sure

- README.md
> Add django-htmlmin

- README.md
> fix: React95

- README.md
> Add querido-diario project

- README.md
> added scanapi

- README.md
> Add Links de Estudo by Nerd0000

- README.md
Neovim was made by a brazilian: Thiago Arruda
> Add Neovim

- README.md
> Add Awesome Hacktoberfest to list

- README.md
> Add Brasil API to the list

- README.md
- **[awsome-csirt](https://github.com/Spacial/csirt)** by [Spacial](https://github.com/Spacial/)
Awesome-CSIRT is an awesome curated list of links and resources in security and csirt daily activities. 
> added awsome-csirts on Readme.md

- README.md
> Add vue-page-title from vinicius73

- README.md
> Add awesome-mlops by kelvins

- README.md
> Added bgslibrary

- README.md
> Add Pathom to the Clojure projects list

- README.md
Oi, 
Mais um projeto bacana pelo mesmo autor do Htop eh o gerenciador de pacotes Luarocks que eh vital para projetos Lua.
Valeu.
> Add Luarocks by hishamhm

- README.md
Open source project that I created to help brazilian community that aren't english speakers
> Add cypress-docs-pt-br open source project

- README.md
> Add react-awesome-styled-grid

- README.md
> add piiijs from portujs

- README.md
> add extenso.js from portujs

- README.md
Contribution Checklist:
Very thanks for creating this initiative, there's too much amazing brazilian projects!
And feel free to know about us, the [Nullstack initiative](https://nullstack.app/pt-br)! :)
> Add Nullstack from Christian Mortaro

- README.md
> Add WhatsApp-BOT by Caio Agiani

- README.md
> README: C++: Add cppbrasil/material-de-aprendizado

- README.md
I create this script to add the badges, because I won't do repeated jobs:
https://gist.github.com/terremoth/423c6a48d0fef89133b3646623d4280d
> Add license badges to all projects

- README.md
- [ x] The project was created by the developers born in Brazil
- [ x] The project can't be just a personal, experimental or sample project
- [ x] The project has more than **100 stars** on Github
- [ x] Place them in alphabetical order
- [ x] One repository per PR/contribution - _avoid conflicts and simplify review_
- [ x] Check if your suggestion follows our pattern (title, description, badge), you need to add double blank space after ending line of each line
If they meet the …
> README: Add QHot

- README.md
> Adiciona Pitaya

- README.md
Adicionando o _calculadora do cidadão_ — PR com viés enorme já que sou o criador/mantenedor do pacote : )
> Adiciona Calculadora do Cidadão

- README.md
> add ariakit

- README.md
Olá 👋 
_not quite -- but it has been rewritten and maintained by me in the last 5+ years_
Espero que esta adição seja  OK 🙂
> Add concurrently

- README.md
> Adds Awesome SEO by Teles

- README.md
> Add LangFlow to README.md

- README.md
> Add Rio terminal

- README.md
> docs: add new repositories

- README.md
> Add awesome-canvas

- README.md
> Add PL research

- README.md
> docs: add kftray

- README.md
> Add Bend programming language by VictorTaelin

- README.md
> docs: add quint

- README.md
> docs: add awesome-shadcn-ui

- README.md
[**GitHub Brasil**](https://www.threads.net/@githubbrasil) recently [indicated this repository](https://www.threads.net/@githubbrasil/post/DGTODdAxCyg) and I'd love if [**Poku**](https://github.com/wellwelwel/poku), our Brazilian test runner, could be part of it 🐷✨
---
> docs: add Poku

- README.md
Mudanças incluem:
* Atualizado o link do repositório do LangFlow no GitHub para `https://github.com/langflow-ai/langflow`.
* Atualizada a descrição do projeto para:
`“Langflow é um construtor de aplicações de low-code para aplicações de RAG e IA multiagente. É baseado em Python e compatível com qualquer modelo, API ou banco de dados.”`
* Traduzida a descrição para o português.
Muito bom ver a quantidade de projetos BR! Sucesso @felipefialho!
> Update Langflow description and links

- README.md
> docs: add expressots

- README.md
> dcos: add css2wind project

- README.md
> Change Dynaconf URLs

- README.md
> Higherorder projects

- README.md
Adicionei o repositório Mulheres na Tecnologia como contribuição ao Projeto (atendendo aos critérios de contribuição descritos no README) para divulgação de referências de conteúdos produzidos por mulheres inspiradoras na tecnologia.
Repositório [Mulheres na Tecnologia ](https://github.com/anatechdev/mulheres-na-tecnologia)
Ana Maria | [github.com/anatechdev](https://github.com/anatechdev)
> Add o repositório Mulheres na Tecnologia

- README.md
> docs: add luxacss

- README.md
Add marmite static site generator in Rust
- **[Marmite](https://github.com/rochacbruno/marmite/)** by [rochacbruno](https://github.com/rochacbruno)  
A Static Site Generator for blogs that is simple, fast and written in Rust  
[![license](https://img.shields.io/github/license/rochacbruno/marmite.svg)](/LICENSE)
> Add Marmite

- README.md
> Add django-ai-assistant by Vinta Software

- README.md
> docs: add buildcli
